# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ function for building a density mixture, given mixture weights and functions.
#' @keywords internal
densityMixture <- function(weights, densities) {
    .Call('_psplinePsd_densityMixture', PACKAGE = 'psplinePsd', weights, densities)
}

