# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ function for calculating the sum of the log of two log-values,i.e., logplus(log(a),log(b))=log(a+b).
#' @keywords internal
logplus <- function(x, y) {
    .Call(`_psplinePsd_logplus`, x, y)
}

#' C++ function for ...
#' @keywords internal
logplusvec <- function(x) {
    .Call(`_psplinePsd_logplusvec`, x)
}

#' C++ function for building a density mixture, given mixture weights and functions.
#' @keywords internal
densityMixture <- function(weights, densities) {
    .Call(`_psplinePsd_densityMixture`, weights, densities)
}

#' C++ help function to redundantly roll out a PSD to length n
#' @keywords internal
unrollPsd <- function(qPsd, n) {
    .Call(`_psplinePsd_unrollPsd`, qPsd, n)
}

